### ISSUE TITLE
Find available port

### ISSUE THREAD

**Issue by alphaville** [alphaville/optimization-engine#114]
The user can specify a desired port with an option `allow_free_port_discovery`; when activated, OpEn will bind at the next available port. This will allow the user to start multiple OpEn TCP servers without the need to explicitly specify different port. Each port will be stored in the local YAML file of the solver, so the client will know at which port to bind.

When building a TCP server to run remotely, `allow_free_port_discovery` should be most probably disabled.

**Comment by chutchi2** [comment]
@alphaville, lets do this

**Comment by chutchi2** [comment]
@alphaville, i'm behind on stuff but i'm starting tonight

**Comment by alphaville** [comment]
@chutchi2 no worries. If you need to discuss anything, you can reach me on [gitter] tomorrow, or you can drop a comment here.

[gitter]: https://gitter.im/alphaville/optimization-engine?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
