### ISSUE TITLE
Cast JSON response in Python into appropriate object

### ISSUE THREAD

**Issue by alphaville** [alphaville/optimization-engine#127]
Currently `OptimizerTcpManager.call` returns a dictionary. We should convert the response of the TCP server into an appropriate object.

We will need some classes, such as (indicatively):

- `SolverStatus` (status of the solver, exit flag, solution, number of inner/outer iterations, etc)
- `SolverError`
- `SolverResponse`, which will store either a `SolverStatus` or a `SolverError` and will be equipped with methods like `is_ok()`, `is_err()` and `get_solver_status()` /  `get_solver_error()` (or simply `get()`)

**Comment by chutchi2** [comment]
@alphaville, would you like me to see if I can knock this out?

**Comment by alphaville** [comment]
@chutchi2 thank you very much for your interest, but this is almost complete in PR #144. Would you be interested in #114?

**Comment by chutchi2** [comment]
@alphaville sure!
