### ISSUE TITLE
ROS CMakefile template

### ISSUE THREAD

**Issue by gmsanchez** [alphaville/optimization-engine#149]
Hi! I've been able to migrate a MHE problem that I had running on IPOPT to OpEn. So far so good, I am able to get results in less than a millisecond!

The next step should be to use the generated C code with roscpp in a ROS C++ node. Is there any template or example on how to configure the CMakefile (using cmake or cmake_simple)?

Thanks in advance!

**Comment by alphaville** [comment]
Hi @gmsanchez. This is great news.

OpEn can generate C/C++ bindings if you compile using the setting `.with_build_c_bindings()` as discussed in the [documentation](https://alphaville.github.io/optimization-engine/docs/python-c). For that you need to install [clang](https://alphaville.github.io/optimization-engine/docs/installation), which is a requirement of `cbindgen`.

OpEn will generate C bindings as well as an [example C file](https://alphaville.github.io/optimization-engine/docs/python-c#bindings-api). You may then modify this file. Compiling and linking is easy, but I think it would be a very good idea for OpEn to auto-generate a cmake file as well.

**Comment by alphaville** [comment]
@gmsanchez  I created a pull request to address this issue. As a first step, I am auto-generating a CMakeLists file that allows you to compile the auto-generated example C file. Once you compile using `with_build_c_bindings()`, you can do:

```bash
cmake .
make run
```

to run the auto-generated example.

This is a first-step to an auto-generated ROS node.

**Comment by alphaville** [comment]
**Note:** See [ros_optimization_engine](https://github.com/gmsanchez/ros_optimization_engine)

**Comment by alphaville** [comment]
First implementation: https://github.com/alphaville/open_ros

It remains to make Jinja2 templates and support automatic code generation for ROS packages
