### ISSUE TITLE
A method to monitor the running solver cost

### ISSUE THREAD

**Issue by strimble08** [alphaville/optimization-engine#176]
When using the OpEn solver I need to read the total cost at each time step.

A feature that can monitor the running cost, which is calculated using the cost functions provided to the solver. Similar to how solution values are called (solver_status.f1_infeasibility, etc).

**Comment by alphaville** [comment]
This is under development in branch `feature/176`

Necessary steps:

- [ ] Implement method `compute_cost_at_solution` in `alm_optimizer.rs`
- [ ] Add field `cost` in `AlmOptimizerStatus`
- [ ] Assign cost value to solution status (in `AlmOptimizer::solve`)
- [ ] Export cost value via TCP interface
- [ ] Read value in TCP client
- [ ] Export value over C/C++ interface (update C bindings)
- [ ] Export value over ROS interface

**Comment by BjoernLindqvist** [comment]
This issue is very similar to my own, so I will just comment it here: It would be very valuable and convenient to be able to directly get the cost value of the optimized/converged solution as part of the tcp-message for any stochastic optimization or "trajectory validation" application.

**Comment by alphaville** [comment]
@BjoernLindqvist Certainly that will be useful. It's already in the pipeline. I have implemented some necessary things in Rust, so it only remains to expose that information over the various interfaces (see checklist above). I think this should be done in a matter of a few days.
