### ISSUE TITLE
Migrate the repository to GitHub Actions instead of Travis CI

### ISSUE THREAD

**Issue by korken89** [alphaville/optimization-engine#223]
With Travis CI shutting down we need to migrate to GitHub Actions, I have done this for many repositories so I'll fix a PR.

**Comment by alphaville** [comment]
I see on their website they've written that "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com." Are they actually shutting down?

In any case, 👍 - it will be a good idea to move things to GitHub actions anyway.

**Comment by korken89** [comment]
They are shutting down the free service, so you have to pay.
GHA is free :)

**Comment by alphaville** [comment]
Let's add this to the README:

![Continuous integration](https://github.com/alphaville/optimization-engine/workflows/Continuous%20integration/badge.svg)
