### ISSUE TITLE
tar.gz file for 0.6.4 doesn't contain the VERSION file

### ISSUE THREAD

**Issue by marioyc** [alphaville/optimization-engine#230]
**Describe the bug**

The [VERSION file](https://github.com/alphaville/optimization-engine/blob/master/open-codegen/VERSION) is missing in the [tar.gz file](https://pypi.org/project/opengen/#files) for version 0.6.4, which causes the installation to fail when running setup.py

**To Reproduce**

1. Download tar.gz file from: https://pypi.org/project/opengen/#files
2. Run setup.py
3. See error

**Additional context**

Pip happened to download the tar.gz instead of the wheel because of some additional options in a project, and opengen's installation started failing, which hadn't previously happened

**Comment by alphaville** [comment]
If you install `opengen` with `pip install opengen` this doesn't happen. However, you're right, `VERSION` is indeed missing. I just uploaded version 0.6.5 where this is fixed.
