### ISSUE TITLE
Compilation speed using Python build interfaces

### ISSUE THREAD

**Issue by xeonz1** [alphaville/optimization-engine#258]
Hi,

The building when using with python interfaces seems slow even when with debug mode. Do the compiler rebuild every time the build() is called? Is there an incremental compile way?

**Comment by alphaville** [comment]
Hi @xeonz1. The slow compilation speed has to do with how the Rust compiler works, not with the Python interface. The compiler doesn't rebuild the code every time, though, so after the first time you compile it should be faster (unless you are using `.with_rebuild()`).
