### ISSUE TITLE
could not find a version satisfies the requirement casadi

### ISSUE THREAD

**Issue by hitdezhazha** [alphaville/optimization-engine#276]
When "pip3 install opengen"
there comes the error as follows:
![image](https://user-images.githubusercontent.com/39644572/178885754-cbc7c190-4357-4a3d-a7fa-10f5dc05bc4f.png)
my raspberrypi is 4B and is 64bit

**Comment by alphaville** [comment]
This seems to be related to casadi, not opengen. In any case, I would recommend that you install opengen within a virtual environment.
