### ISSUE TITLE
roslaunch husky_gazebo husky_empty_world.launch

### ISSUE THREAD

**Issue by HatemRaya** [alphaville/optimization-engine#322]
![Untitled](https://user-images.githubusercontent.com/120754863/232088114-ca351809-3e08-4f9e-91f2-7cfc25181f4e.jpeg)
Dear all

i am a beginner in Ros and Ubuntu and i was trying to install husky mobile robot for my project and launch it by Ros in gazebo so after successfully installing husky desktop and husky simulator i tried to launch the husky in gazebo by this sequence:

```
sudo apt-get install ros-noetic-husky-desktop
sudo apt-get install ros-noetic-husky-simulator
roslaunch husky_gazebo husky_empty_world.launch
```

but, with executing the last code i faced this error

```
RLException: [husky_empty_world.launch] is neither a launch file in package [husky_gazebo] nor is [husky_gazebo] a launch file name
The traceback for the exception was written to the log file
```

**Comment by alphaville** [comment]
Hatem, I believe @gmsanchez (who wrote this part of the code) will be better suited to help. I will transfer this issue to https://github.com/gmsanchez/open_ros_codegen.

**Comment by alphaville** [comment]
@HatemRaya, apparently I cannot transfer the issue to https://github.com/gmsanchez/open_ros_codegen, but I would encourage you to ask there. 

I'm assuming that you are trying to run [this example](https://alphaville.github.io/optimization-engine/docs/example_navigation_ros_codegen).

**Comment by gmsanchez** [comment]
Hi, @HatemRaya
I have never installed Husky packages using apt. Have you tried following the instructions on the example that @alphaville mentions? They might be a little outdated, but the main difference is using the Husky code from Clearpath's Github repository.

Please, try that way and let me know how it goes
