### ISSUE TITLE
Cartesian product of constraints

### ISSUE THREAD

**Issue by alphaville** [alphaville/optimization-engine#33]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add support for the Cartesian product of constraints in Rust and then in Python and MATLAB. This will allow to support products of Rectangles and Euclidean balls.

**Describe alternatives you've considered**
The Cartesian product of constraints will map indices to instances of `ConstraintType`

**Additional context**
None

**Comment by korken89** [comment]
I think this is merged, can we close this? @alphaville

**Comment by alphaville** [comment]
@korken89 Yes, it's merged indeed. I'm closing this.
