### ISSUE TITLE
Improve docs to differentiate with_constraints and with_penalty_constraints

### ISSUE THREAD

**Issue by korken89** [alphaville/optimization-engine#62]
Currently in the documentation it is not quite clear, and I have already seen code where people only use penalty constraints (even for simple bounds on the decision variables).
I think we need to have a small guidelines section, like follow a 1. 2. 3. to make a normal solver to guide people through the process :)

**Comment by alphaville** [comment]
@korken89 You mean that there might be some confusion between constraints of the form `u in U` and `c(u, p) = 0`?

**Comment by alphaville** [comment]
@korken89 I guess we can close this, right?

**Comment by korken89** [comment]
Yeah
