### ISSUE TITLE
OpEn installation requirements (bindgen)

### ISSUE THREAD

**Issue by alphaville** [alphaville/optimization-engine#72]
I got an email from a user who tried to run OpEn on Windows and got the following message:

![image](https://user-images.githubusercontent.com/125415/63170085-67908b00-c030-11e9-90d0-e437025cf452.png)

[Bindgen's documentation](https://github.com/rust-lang/rust-bindgen/blob/master/book/src/requirements.md) says that `clang` is a requirement. In fact they recommend version 3.9. Do we need to state this as a requirement for OpEn?

**Comment by korken89** [comment]
Yes, this is indeed a requirement so we should add it.

**Comment by alphaville** [comment]
I will now update the website.
